# Generated by Django 4.2.7 on 2023-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=80, verbose_name="Email")),
                (
                    "job_zone",
                    models.TextField(blank=True, null=True, verbose_name="Job Zone"),
                ),
                (
                    "carrer",
                    models.TextField(blank=True, null=True, verbose_name="Career"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
            ],
            options={
                "verbose_name": "Dados",
                "verbose_name_plural": "Dados",
                "ordering": ["-pk"],
            },
        ),
    ]
