# Generated by Django 4.2.7 on 2023-12-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dados",
            name="answers",
            field=models.TextField(blank=True, null=True, verbose_name="Answers"),
        ),
    ]
